apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: k8s-example
  name: provider-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider-service
  template:
    metadata:
      labels:
        app: provider-service
    spec:
      containers:
        - name: provider-service
          image: wangcaitao/provider-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          envFrom:
            - configMapRef:
                name: common-configmap
